planned_index:
    path: /index
    defaults: { _controller: JBPlannedBundle:Planned:plannedIndex }

planned_list:
    path: /list
    defaults: { _controller: JBPlannedBundle:Planned:plannedList }

planned_view:
    path: /view
    defaults: { _controller: JBPlannedBundle:Planned:plannedView }

planned_add:
    path: /add
    defaults: { _controller: JBPlannedBundle:Planned:plannedAdd }

planned_edit:
    path: /edit{id}
    defaults: { _controller: JBPlannedBundle:Planned:plannedEdit }
    requirements:
        id: \d+

planned_delete:
    path: /delete/{id}
    defaults: { _controller: JBPlannedBundle:Planned:plannedDelete }
    requirements:
            id: \d+
