jb_user:
    resource: "@JBUserBundle/Resources/config/routing.yml"
    prefix:   /

jb_planned:
    resource: "@JBPlannedBundle/Resources/config/routing.yml"
    prefix:   /planned

#login:
#   pattern:   /login
#    defaults:  { _controller: JBUserBundle:Security:login }

#login_check:
#    pattern:   /login_check

logout:
    pattern:   /logout

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

twitter_login:
    pattern: /login/check-twitter

facebook_login:
    pattern: /login/check-facebook

