<?php

namespace JB\PlannedBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlannedTweetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlannedTweetsRepository extends EntityRepository
{
}
